# bin2h.cmake — Convert a binary file to a C header with embedded byte array.
#
# Usage:
#   cmake -DINPUT_FILE=<path> -DOUTPUT_FILE=<path> -DVAR_NAME=<identifier> -P bin2h.cmake
#
# Produces a header file containing:
#   static const unsigned char <VAR_NAME>[] = { 0x.., 0x.., ... };
#   static const size_t <VAR_NAME>_size = <N>;

if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE not defined")
endif()
if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE not defined")
endif()
if(NOT DEFINED VAR_NAME)
    message(FATAL_ERROR "VAR_NAME not defined")
endif()

file(READ "${INPUT_FILE}" content HEX)
string(LENGTH "${content}" content_length)
math(EXPR byte_count "${content_length} / 2")

# Convert hex pairs to 0x.. format with commas
set(output "")
set(line "")
set(col 0)
math(EXPR last_index "${content_length} - 2")
foreach(i RANGE 0 ${last_index} 2)
    string(SUBSTRING "${content}" ${i} 2 byte)
    if(col GREATER 0)
        string(APPEND line ",")
    endif()
    string(APPEND line "0x${byte}")
    math(EXPR col "${col} + 1")
    if(col EQUAL 16)
        string(APPEND output "    ${line},\n")
        set(line "")
        set(col 0)
    endif()
endforeach()
if(col GREATER 0)
    string(APPEND output "    ${line}\n")
endif()

# Write the header file
file(WRITE "${OUTPUT_FILE}"
    "// Auto-generated by bin2h.cmake — do not edit.\n"
    "#pragma once\n"
    "#include <stddef.h>\n"
    "\n"
    "static const unsigned char ${VAR_NAME}[] = {\n"
    "${output}"
    "};\n"
    "static const size_t ${VAR_NAME}_size = ${byte_count};\n"
)
