# txt2h.cmake — Convert a text file to a C++ header with an embedded raw
# string literal.
#
# Usage:
#   cmake -DINPUT_FILE=<path> -DOUTPUT_FILE=<path> -DVAR_NAME=<identifier> -P txt2h.cmake
#
# Produces a header file containing:
#   static const char <VAR_NAME>[] = R"GHOST_TXT2H(<file contents>)GHOST_TXT2H";
#   static const size_t <VAR_NAME>_size = sizeof(<VAR_NAME>) - 1;
#
# The array is null-terminated; <VAR_NAME>_size excludes the terminator and
# matches the original file's byte count. Use this for sources that are
# consumed as text (PTX, OpenCL C, GLSL, etc.); for binary blobs use bin2h.

if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE not defined")
endif()
if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE not defined")
endif()
if(NOT DEFINED VAR_NAME)
    message(FATAL_ERROR "VAR_NAME not defined")
endif()

set(delim "GHOST_TXT2H")

file(READ "${INPUT_FILE}" content)

# Guard against the closing delimiter appearing inside the content, which
# would terminate the raw string early.
string(FIND "${content}" ")${delim}\"" collision)
if(NOT collision EQUAL -1)
    message(FATAL_ERROR
        "txt2h: delimiter ')${delim}\"' appears in ${INPUT_FILE}; "
        "pick a different delimiter")
endif()

file(WRITE "${OUTPUT_FILE}"
    "// Auto-generated by txt2h.cmake — do not edit.\n"
    "#pragma once\n"
    "#include <stddef.h>\n"
    "\n"
    "static const char ${VAR_NAME}[] = R\"${delim}(${content})${delim}\";\n"
    "static const size_t ${VAR_NAME}_size = sizeof(${VAR_NAME}) - 1;\n"
)
